spring.application.name=ProductShop

spring.datasource.url=jdbc:mysql://localhost:3306/pdbtest
spring.datasource.username=root
spring.datasource.password=seucse613

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true