spring.application.name=Arekta Notun Project

spring.datasource.url=jdbc:mysql://localhost:3306/anpsp26
spring.datasource.username=root
spring.datasource.password=seucse613

spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=java
spring.security.user.password=1234
